services:
  auth:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: difelix
      POSTGRES_DB: soccer-club-census-db
    ports:
      - "5432:5432"